baseURL = "https://tiger-pillow.github.io/"
languageCode = "en-us"
title = "Gladys Fang"
theme = "yinyang"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[author]
  name = "Gladys" 

[params]
headTitle = "Gladys Fang's stuff"
Subtitle = "Nothing ever becomes real till it is experienced." 
mainSections = ["post"]
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'

[[params.socials]]
name = "About Me"
link = "https://tiger-pillow.github.io/aboutGladys/about"
